<?php
/**
 * Created by PhpStorm.
 * User: chenmingming
 * Date: 2017/1/16
 * Time: 14:27
 */

namespace tests\admin\api\common;

class test extends \mmapi\api\Test
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->url = 'http://admin.football.chenmm.cn/common/test.json';
        $this->addParam('id', 1);
    }

    public function testBase()
    {
        $this->request();
        $this->assertEquals(200, $this->reponse->getStatusCode());
    }
}